import { useEffect, useState, type ReactNode } from 'react';
import { ArrowUpRight, Check, ChevronRight, Eye, EyeOff, Globe2, Keyboard, KeyRound, Laptop, LockKeyhole, Mic, Moon, RefreshCw, ShieldCheck, Sun } from 'lucide-react';
import { call, desktop } from '../lib/api';
import { ProviderIcon, Shortcut, Toggle } from '../components/ui';
import type { KeyStatus, Microphone, Provider, Settings as Preferences } from '../lib/types';

function Row({title,description,children}:{title:string;description?:string;children:ReactNode}) {return <div className="settings-row"><div><h3>{title}</h3>{description&&<p>{description}</p>}</div><div className="row-control">{children}</div></div>;}
function ApiKey({provider,status,refresh,toast}:{provider:Provider;status:KeyStatus[Provider];refresh:()=>void;toast:(message:string)=>void}) {
  const [value,setValue]=useState('');const [show,setShow]=useState(false);const [pending,setPending]=useState(false);
  async function save(remove=false){setPending(true);try{await call(remove?'remove_key':'save_key',remove?{provider}:{provider,key:value});setValue('');refresh();toast(remove?'Chave removida.':'Chave salva no chaveiro do Linux.');}catch(e){toast(String(e));}finally{setPending(false);}}
  return <div className="api-key-card"><div className="provider-heading"><ProviderIcon provider={provider}/><div><h3>{provider==='openai'?'OpenAI':'Gemini'}</h3><small>{status.saved?'Chave salva no chaveiro':'Use sua própria chave de API'}</small></div>{status.saved?<span className="badge active-badge"><Check size={12}/>Adicionada</span>:<span className="badge">Não conectada</span>}</div>
    <form onSubmit={e=>{e.preventDefault();void save();}}><div className="key-input"><KeyRound size={16}/><input type={show?'text':'password'} aria-label={`Chave da API ${provider==='openai'?'OpenAI':'Gemini'}`} value={value} onChange={e=>setValue(e.target.value)} placeholder={status.saved?'Cole uma nova chave para substituir':'Cole sua chave de API'} autoComplete="off" spellCheck={false} disabled={!desktop||pending}/><button type="button" className="icon-button" aria-label={show?'Ocultar chave':'Mostrar chave'} onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></div><div className="api-key-actions"><a href={provider==='openai'?'https://platform.openai.com/api-keys':'https://aistudio.google.com/apikey'} target="_blank" rel="noreferrer">Obter chave<ArrowUpRight size={13}/></a><div>{status.saved&&<button type="button" className="text-link danger" disabled={pending} onClick={()=>save(true)}>Remover</button>}<button className="button secondary small-button" disabled={!value.trim()||pending}>{pending?'Salvando…':'Salvar chave'}</button></div></div></form>
    {status.error&&<p className="field-error">{status.error}</p>}
  </div>;
}

export function Settings({settings,keys,extensionConnected,refresh,toast,busy}:{settings:Preferences;keys:KeyStatus;extensionConnected:boolean;refresh:()=>void;toast:(text:string)=>void;busy:boolean}) {
  const [draft,setDraft]=useState(settings);const [saving,setSaving]=useState(false);
  const [microphones,setMicrophones]=useState<Microphone[]>([{id:'default',name:'Padrão do sistema'}]);const [micError,setMicError]=useState('');
  useEffect(()=>setDraft(settings),[settings]);
  const change=<K extends keyof Preferences>(key:K,value:Preferences[K])=>setDraft(old=>({...old,[key]:value}));
  async function loadMicrophones(){setMicError('');try{setMicrophones(await call('list_microphones'));}catch(e){setMicError(String(e));}}
  useEffect(()=>{void loadMicrophones();},[]);
  const dirty=JSON.stringify(draft)!==JSON.stringify(settings);
  async function save(){setSaving(true);try{await call('save_settings',{settings:draft});refresh();toast('Configurações salvas.');}catch(e){toast(String(e));}finally{setSaving(false);}}
  return <div className="page settings-page"><div className="page-heading"><div><div className="eyebrow">DO SEU JEITO</div><h1>Configurações</h1><p>O essencial para falar e continuar.</p></div><button className="button primary" disabled={!dirty||saving||busy} onClick={save}>{saving?'Salvando…':dirty?'Salvar alterações':'Tudo salvo'}{!dirty&&<Check size={15}/>}</button></div>
    {!desktop&&<div className="notice"><Laptop size={18}/><span>Prévia da interface. Adicione suas chaves e configure o microfone no aplicativo Linux.</span></div>}
    <div className="settings-section-title"><KeyRound size={17}/><h2>Provedores de transcrição</h2></div>
    <div className="api-keys-grid">{(['openai','gemini'] as Provider[]).map(provider=><ApiKey key={provider} provider={provider} status={keys[provider]} refresh={refresh} toast={toast}/>)}</div>
    <div className="privacy-note"><LockKeyhole size={13}/>As chaves ficam no chaveiro do Linux. O áudio vai direto para o provedor escolhido.</div>
    <fieldset disabled={busy||saving}>
      <section className="settings-card"><Row title="Provedor ativo" description="Você pode manter as duas chaves adicionadas."><div className="segmented"><button className={draft.provider==='openai'?'selected':''} onClick={()=>change('provider','openai')}>OpenAI</button><button className={draft.provider==='gemini'?'selected':''} onClick={()=>change('provider','gemini')}>Gemini</button></div></Row>
        <Row title="Modelo" description="Transcrição fiel, no idioma falado.">{draft.provider==='openai'?<select aria-label="Modelo de transcrição" value={draft.openaiModel} onChange={e=>change('openaiModel',e.target.value)}><option value="gpt-transcribe">GPT Transcribe</option><option value="gpt-4o-transcribe">GPT-4o Transcribe</option><option value="gpt-4o-mini-transcribe">GPT-4o Mini Transcribe</option></select>:<select aria-label="Modelo de transcrição" value={draft.geminiModel} onChange={e=>change('geminiModel',e.target.value)}><option value="gemini-3.5-transcribe">Gemini 3.5 Transcribe</option></select>}</Row>
        <Row title="Idioma" description="Ajuda o modelo a reconhecer o que você fala."><span className="select-icon"><Globe2 size={16}/><select aria-label="Idioma" value={draft.language} onChange={e=>change('language',e.target.value)}><option value="auto">Detectar automaticamente</option><option value="pt-BR">Português (Brasil)</option><option value="en-US">English</option><option value="es-ES">Español</option><option value="ja-JP">日本語</option></select></span></Row>
      </section>
      <div className="settings-section-title"><Keyboard size={17}/><h2>Atalho e gravação</h2></div>
      <section className="settings-card"><Row title="Atalho para ditar" description="Funciona enquanto você usa outros aplicativos."><select aria-label="Atalho para ditar" value={draft.shortcut} onChange={e=>change('shortcut',e.target.value)}><option value="<Control><Super>space">Ctrl + Super + Espaço</option><option value="<Control><Alt>space">Ctrl + Alt + Espaço</option><option value="<Super><Shift>d">Super + Shift + D</option><option value="<Control><Shift>F9">Ctrl + Shift + F9</option></select></Row>
        <div className="mode-choices"><button className={`mode-choice ${draft.mode==='toggle'?'selected':''}`} onClick={()=>change('mode','toggle')}><span className="radio-circle"/><div><strong>Apertar para alternar</strong><p>Aperte para começar. Aperte de novo ou Enter para enviar.</p></div></button><button className={`mode-choice ${draft.mode==='hold'?'selected':''}`} onClick={()=>change('mode','hold')}><span className="radio-circle"/><div><strong>Segurar para falar</strong><p>Segure o atalho enquanto fala. Solte para enviar.</p></div></button></div><div className="inline-hint"><kbd>Esc</kbd> cancela e descarta o áudio, sem enviar à API.</div>
        <Row title="Colar ao finalizar" description="Cola na janela de origem e mantém o texto no Ctrl + V."><Toggle label="Colar ao finalizar" checked={draft.autoPaste} onChange={v=>change('autoPaste',v)}/></Row>
      </section>
      <div className="settings-section-title"><Mic size={17}/><h2>Microfone</h2></div>
      <section className="settings-card"><Row title="Dispositivo de entrada" description="O padrão acompanha a configuração do sistema."><select aria-label="Microfone" value={draft.microphone} onChange={e=>change('microphone',e.target.value)}>{!microphones.some(m=>m.id===draft.microphone)&&<option value={draft.microphone}>Microfone desconectado</option>}{microphones.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select><button className="icon-button" aria-label="Atualizar microfones" onClick={loadMicrophones}><RefreshCw size={16}/></button></Row>{micError&&<p className="field-error padded">{micError}</p>}
        <Row title="Remover pausas" description="Ignora silêncios longos. Retoma quando você volta a falar."><Toggle label="Remover pausas" checked={draft.trimSilence} onChange={v=>change('trimSilence',v)}/></Row>
        {draft.trimSilence&&<Row title="Filtro de ruído" description="Se palavras forem cortadas, use um filtro mais leve."><select aria-label="Filtro de ruído" value={draft.vadMode} onChange={e=>change('vadMode',Number(e.target.value))}><option value={0}>Leve</option><option value={1}>Equilibrado</option><option value={2}>Forte</option><option value={3}>Muito forte</option></select></Row>}
      </section>
      <div className="settings-section-title"><Sun size={17}/><h2>Aparência</h2></div><section className="settings-card"><Row title="Tema" description="Um espaço confortável para suas ideias."><div className="segmented theme-picker">{[{id:'light',label:'Claro',icon:<Sun size={15}/>},{id:'dark',label:'Escuro',icon:<Moon size={15}/>},{id:'system',label:'Sistema',icon:<Laptop size={15}/>}].map(theme=><button key={theme.id} className={draft.theme===theme.id?'selected':''} onClick={()=>change('theme',theme.id as Preferences['theme'])}>{theme.icon}{theme.label}</button>)}</div></Row></section>
    </fieldset>
    <section className={`integration-card ${extensionConnected?'is-connected':''}`}><ShieldCheck size={23}/><div><h3>{extensionConnected?'Integração GNOME conectada':'Conecte a extensão GNOME'}</h3><p>{extensionConnected?'Atalhos, janela flutuante e colagem disponíveis no Wayland.':'Instale a extensão incluída no projeto para usar atalhos e colagem no Wayland.'}</p>{!extensionConnected&&<code>npm run extension:install</code>}</div>{extensionConnected?<Check size={20}/>:<ChevronRight size={20}/>}</section>
    <div className="settings-summary"><Shortcut value={draft.shortcut}/><span>para ditar · <kbd>Esc</kbd> para cancelar</span></div>
    {dirty&&<div className="save-bar"><span>Você tem alterações não salvas.</span><button className="button primary" disabled={saving||busy} onClick={save}>Salvar alterações</button></div>}
  </div>;
}
